-- ==============================================
-- DATA SEED UNTUK SUPABASE
-- FORMAT SPECIAL: UNTUK KOLOM BERTYPE text[]
-- ==============================================
-- Jalankan file ini jika tipe kolom requirements & skills_required Anda adalah text[]
-- ==============================================

-- 1. SEED COMPANIES
INSERT INTO public.companies (id, name, logo, description, industry, location, website, is_verified) VALUES
('co-1', 'Google Cloud Platform', 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=100&auto=format&fit=crop&q=60', 'Leading global cloud computing technology suite by Google.', 'Technology', 'Mountain View, CA', 'https://cloud.google.com', true),
('co-2', 'Finverge Labs', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=60', 'Next-generation banking tech solutions and open-finance ledgers.', 'Financial Technology', 'Singapore, SG', 'https://finverge.io', true),
('co-3', 'Veritas Analytics', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&auto=format&fit=crop&q=60', 'Big data consultancy with focus on predictive modeling and health analytics.', 'Data Science', 'Jakarta, ID', 'https://veritasanalytica.id', true),
('co-4', 'CryptoApex Global Inc. (SUSPICIOUS)', 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=100&auto=format&fit=crop&q=60', 'Web3 and Bitcoin growth optimization agency. Direct bank wire is required for software tooling integration training setup fees.', 'Web3 & Marketing', 'Offshore Office', 'http://cryptoapex-pay-scam.com', false),
('co-5', 'Tokopedia', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=100&auto=format&fit=crop&q=60', 'Leading Indonesian e-commerce platform empowering millions of small businesses.', 'E-commerce', 'Jakarta, ID', 'https://www.tokopedia.com', true),
('co-6', 'GoTo Group', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=60', 'The largest technology group in Indonesia, combining on-demand services, e-commerce, and financial services.', 'Technology', 'Jakarta, ID', 'https://www.gotocompany.com', true),
('co-7', 'Traveloka', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=100&auto=format&fit=crop&q=60', 'Southeast Asia''s leading lifestyle superapp providing travel, local services, and financial products.', 'Travel & Lifestyle', 'Jakarta, ID', 'https://www.traveloka.com', true),
('co-8', 'Bank Mandiri', 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=60', 'Largest state-owned bank in Indonesia with top tier corporate financing and digital retail products.', 'Banking & Financial', 'Jakarta, ID', 'https://www.bankmandiri.co.id', true),
('co-9', 'Shopee Indonesia', 'https://images.unsplash.com/photo-1472851294608-062f824d296e?w=100&auto=format&fit=crop&q=60', 'Vibrant online mobile-first retail ecosystem driving digitisation throughout Southeast Asia.', 'E-commerce', 'Jakarta, ID', 'https://shopee.co.id', true),
('co-10', 'Bukalapak', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=100&auto=format&fit=crop&q=60', 'Supporting MSMEs and local neighborhood groceries (warungs) in Indonesia through digital retail services.', 'E-commerce / FinTech', 'Bandung, ID', 'https://www.bukalapak.com', true),
('co-11', 'Vidio', 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=100&auto=format&fit=crop&q=60', 'Leading Indonesian over-the-top streaming service airing local soap operas, premium league matches, and movies.', 'Media & Streaming', 'Jakarta, ID', 'https://www.vidio.com', true),
('co-12', 'Kopi Kenangan', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=100&auto=format&fit=crop&q=60', 'Top fast-casual coffee chain in Indonesia operating a tech-led smart ordering retail network.', 'Retail Tech / F&B', 'Jakarta, ID', 'https://kopikenangan.com', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, logo = EXCLUDED.logo, description = EXCLUDED.description, industry = EXCLUDED.industry, location = EXCLUDED.location, website = EXCLUDED.website, is_verified = EXCLUDED.is_verified;


-- 2. SEED JOBS (DENGAN FORMAT ARRAY pg)
INSERT INTO public.jobs (id, title, company_id, company_name, company_logo, location, salary_range, job_type, experience_level, description, requirements, skills_required, status, is_suspicious, suspicious_reason, created_at) VALUES
('job-1', 'Senior Fullstack TypeScript Engineer', 'co-1', 'Google Cloud Platform', 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=100&auto=format&fit=crop&q=60', 'Remote (APAC)', '$8,000 - $13,000 / month', 'Remote', 'Senior Level', 'We are looking for a remote developer to build high-scale cloud platforms using React, Node.js, and server-side TypeScript. In this role, you will implement modular microservices and real-time collaboration engines.', ARRAY['5+ years programming experience in React and Node.js', 'Proven expertise with modern build systems and bundlers (Vite/Rspack)', 'Excellent system design capability and database performance optimization skills']::text[], ARRAY['React', 'TypeScript', 'Node.js', 'Vite', 'PostgreSQL', 'Tailwind CSS']::text[], 'approved', false, NULL, '2026-05-17T23:35:24.530Z'),
('job-2', 'Frontend Developer (React & Tailwind)', 'co-2', 'Finverge Labs', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=60', 'Singapore / Hybrid', '$4,500 - $6,000 / month', 'Full-time', 'Mid Level', 'Join Finverge to design and build transactional web dashboards for multi-asset wallets and ledger analytics. You will work in a fast-paced environment with a core stack of React 19, Tailwind CSS, and Framer Motion.', ARRAY['3+ years experience with React Hook form optimization', 'Demonstrated high visual styling fidelity with Tailwind CSS', 'Knowledge of state management such as Zustand or React Context']::text[], ARRAY['React', 'Tailwind CSS', 'Framer Motion', 'Zustand', 'CSS']::text[], 'approved', false, NULL, '2026-05-20T11:35:24.530Z'),
('job-3', 'Urgent Remote Assistant - Weekly High Pay Payout', 'co-4', 'CryptoApex Global Inc.', 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=100&auto=format&fit=crop&q=60', 'Offshore Office / Immediate Start', '$1,000 - $2,500 / week', 'Part-time', 'Entry Level', 'Immediate hiring for virtual marketing assistants. No prior skillset is required! Training fee of $50 must be wired to our platform wallet to unlock premium task dashboard instructions. High commission payouts daily.', ARRAY['Must have stable internet and a bank account', 'Willing to pay $50 training/tooling unlock package up front', 'Work only 1 hour per day and earn thousands']::text[], ARRAY['Marketing', 'Data Entry', 'Telegram']::text[], 'pending', true, 'Requires upfront payment ($50 training fee) to unlock working portal, promises unrealistically high entry-level compensation with no skill requirements, and operates via suspect offshore billing patterns.', '2026-05-20T15:35:24.530Z'),
('job-4', 'Software Engineer - Backend Go & gRPC', 'co-6', 'GoTo Group', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 18.000.000 - Rp 30.000.000 / month', 'Full-time', 'Mid Level', 'Kami sedang mencari Backend Go Developer untuk mengoptimalkan layanan on-demand kami, merawat request throughput tinggi, gRPC api endpoints, dan database SQL/NoSQL berskala besar.', ARRAY['2+ tahun pengalaman kerja dengan Golang', 'Memahami REST API, gRPC, serta protocol buffers', 'Berpengalaman dengan relational database seperti PostgreSQL dan message broker seperti Kafka']::text[], ARRAY['Go', 'gRPC', 'PostgreSQL', 'Kafka', 'Redis', 'Docker']::text[], 'approved', false, NULL, '2026-05-18T23:35:24.530Z'),
('job-5', 'Senior Frontend Engineer (React/NextJS)', 'co-5', 'Tokopedia', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID / Hybrid', 'Rp 25.000.000 - Rp 45.000.000 / month', 'Full-time', 'Senior Level', 'Pimpin pengembangan arsitektur website pembeli Tokopedia menggunakan Next.js dan optimasi Core Web Vitals untuk meningkatkan konversi pengguna dan performa SEO.', ARRAY['5+ tahun pengalaman dalam ekosistem frontend JavaScript', 'Keahlian mendalam mengenai SSR, SSG, heritansi modul Next.js, dan optimasi CSS', 'Leadership yang matang untuk mentoring junior developers']::text[], ARRAY['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'GraphQL', 'Lighthouse']::text[], 'approved', false, NULL, '2026-05-20T03:35:24.530Z'),
('job-6', 'Mobile Developer - Flutter', 'co-7', 'Traveloka', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 14.000.000 - Rp 22.000.000 / month', 'Full-time', 'Mid Level', 'Membangun fungsionalitas pencarian hotel dan pemesanan aktivitas tiket liburan secara dinamis menggunakan Flutter untuk platform Android dan iOS.', ARRAY['Minimal 2 tahun pengalaman komparatif menggunakan Flutter dan Dart', 'Familiar dengan state management Bloc atau Provider', 'Pernah merilis minimal 1 aplikasi ke Play Store atau App Store']::text[], ARRAY['Flutter', 'Dart', 'Android', 'iOS', 'Bloc', 'REST API']::text[], 'approved', false, NULL, '2026-05-20T23:35:24.530Z'),
('job-7', 'Junior Data Analyst', 'co-3', 'Veritas Analytics', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 7.500.000 - Rp 11.000.000 / month', 'Full-time', 'Entry Level', 'Melakukan pembersihan data mentah, mengekstrak metrik performa operasional berkala, serta menyusun dashboard visualisasi menggunakan Tableau atau PowerBI.', ARRAY['Pendidikan minimal S1 Statistika, Matematika, atau Sistem Informasi', 'Lancer dalam menulis query SQL kompleks (JOIN, Subqueries, CTEs)', 'Familiaritas dasar berkomunikasi statistik dalam bahasa Python atau R']::text[], ARRAY['SQL', 'Python', 'Tableau', 'Excel', 'Pandas']::text[], 'approved', false, NULL, '2026-05-20T05:35:24.530Z'),
('job-8', 'Cloud DevOps Practitioner', 'co-6', 'GoTo Group', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=60', 'Remote (Indonesia)', 'Rp 22.000.000 - Rp 38.000.000 / month', 'Remote', 'Senior Level', 'Bertanggung jawab atas otomatisasi pipeline CI/CD, mengawasi klaster orkestrasi Kubernetes di Google Cloud, serta memantau keandalan sistem berskala jutaan user.', ARRAY['Pemahaman luar biasa tentang Terraform, Ansible, dan Docker', 'Sertifikasi GCP Professional Cloud Architect lebih disukai', 'Terbiasa dengan monitoring tools seperti Prometheus dan Grafana']::text[], ARRAY['Kubernetes', 'Docker', 'Terraform', 'GCP', 'GitHub Actions', 'Prometheus']::text[], 'approved', false, NULL, '2026-05-20T18:35:24.530Z'),
('job-9', 'Web Developer (PHP & Laravel)', 'co-10', 'Bukalapak', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=100&auto=format&fit=crop&q=60', 'Bandung, ID / Remote', 'Rp 10.000.000 - Rp 16.000.000 / month', 'Full-time', 'Mid Level', 'Mengembangkan sistem operasional merchant dan inventori logistik penunjang warung-warung menggunakan framework Laravel 11 terintegrasi.', ARRAY['Paham OOP PHP dengan baik dan standar kepatuhan PSR', 'Minimal 2 tahun pengalaman aktif memproduksi modul fungsional di Laravel', 'Terbiasa dengan database MySQL/MariaDB dan integrasi REST backend']::text[], ARRAY['PHP', 'Laravel', 'MySQL', 'JavaScript', 'HTML', 'Git']::text[], 'approved', false, NULL, '2026-05-17T23:35:24.530Z'),
('job-10', 'UI/UX Designer Expert', 'co-11', 'Vidio', 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 12.000.000 - Rp 20.000.000 / month', 'Full-time', 'Mid Level', 'Merancang wireframe, user flow interaktif, serta visual aset modern untuk platform streaming video kami di Web, Mobile App, dan Smart TV web kit.', ARRAY['Portofolio desain UI/UX solid di Figma atau Sketch', 'Mahir melakukan user research dan usability testing pada produk hiburan digital', 'Memahami basic CSS/HTML untuk koordinasi lancar dengan frontend developers']::text[], ARRAY['Figma', 'UI Design', 'Wireframing', 'User Research', 'Prototyping']::text[], 'approved', false, NULL, '2026-05-14T17:35:24.530Z'),
('job-11', 'IT Corporate Security Lead', 'co-8', 'Bank Mandiri', 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 30.000.000 - Rp 50.000.000 / month', 'Full-time', 'Senior Level', 'Mengawasi audit postur keamanan jaringan, kepatuhan infrastruktur perbankan digital Mandiri, serta mengamankan gateway transaksi keuangan dari eksploitasi siber.', ARRAY['Pendidikan S1 Informatika keamanan siber atau kompetensi setara', 'Sertifikasi Certified Information Systems Auditor (CISA) atau CISSP', 'Berpengalaman dengan regulasi perbankan OJK dan kepatuhan ISO 27001']::text[], ARRAY['Cybersecurity', 'Risk Assessment', 'ISO 27001', 'Network Auditing', 'Firewalls']::text[], 'approved', false, NULL, '2026-05-10T23:35:24.530Z'),
('job-12', 'Mobile Developer React Native', 'co-9', 'Shopee Indonesia', 'https://images.unsplash.com/photo-1472851294608-062f824d296e?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID / Hybrid', 'Rp 16.000.000 - Rp 27.000.000 / month', 'Full-time', 'Mid Level', 'Bergabunglah di tim inti Shopee Pay untuk memoles komponen interface pembayaran e-wallet menggunakan React Native dengan optimalisasi runtime memory rendering.', ARRAY['Keahlian mendalam dalam TypeScript dan React Native Native Bridges', 'Familiar dengan Redux Saga atau Toolkit untuk state synchronisation', 'Kemampuan andal mematangkan visual layout responsif multi-device screen']::text[], ARRAY['React Native', 'TypeScript', 'Redux', 'iOS', 'Android', 'Jest']::text[], 'approved', false, NULL, '2026-05-19T17:35:24.530Z'),
('job-13', 'Android Developer (Java/Kotlin)', 'co-5', 'Tokopedia', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 15.000.000 - Rp 25.000.000 / month', 'Full-time', 'Mid Level', 'Ciptakan fitur interaksi produk instan, ulasan gambar, serta tracking ekspedisi logistik kurir real-time pada aplikasi native Android Tokopedia.', ARRAY['Minimal 3 tahun mengemban development native Android Kotlin', 'Memahami Android Jetpack Components dan pola arsitektur MVVM', 'Terbiasa melakukan profiling memori menggunakan Android Studio tools']::text[], ARRAY['Kotlin', 'Android SDK', 'Java', 'MVVM', 'Retrofit', 'Coroutines']::text[], 'approved', false, NULL, '2026-05-20T09:35:24.530Z'),
('job-14', 'iOS Platform Engineer', 'co-6', 'GoTo Group', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 18.000.000 - Rp 32.000.000 / month', 'Full-time', 'Senior Level', 'Pahat kode tangguh untuk aplikasi Gojek pelanggan di ekosistem iOS menggunakan Swift modern, SwiftUI, serta struktur concurrency modern (async/await).', ARRAY['4+ tahun menulis program iOS native komersial', 'Pemahaman kuat atas memory leaks management (retain cycles, ARC)', 'Pengalaman rilis TestFlight dan App Store submission']::text[], ARRAY['Swift', 'SwiftUI', 'XCode', 'Combine', 'iOS SDK', 'Cocoapods']::text[], 'approved', false, NULL, '2026-05-16T19:35:24.530Z'),
('job-15', 'Machine Learning Deep Learning Specialist', 'co-3', 'Veritas Analytics', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&auto=format&fit=crop&q=60', 'Remote (Indonesia)', 'Rp 20.000.000 - Rp 35.000.000 / month', 'Remote', 'Senior Level', 'Latih model prediksi risiko kredit perbankan, deteksi fraud transaksi keuangan, serta model NLP teks berkas dengan Python, PyTorch, dan Docker.', ARRAY['Gelar S2/S3 bidang Ilmu Komputer, Matematika, Data Science atau setara', 'Pengalaman hands-on melatih model deep learning dan machine learning klasik', 'Keahlian mumpuni memicu deployment model ke AWS SageMaker atau GCP Vertex AI']::text[], ARRAY['Python', 'PyTorch', 'TensorFlow', 'Scikit-Learn', 'Docker', 'Machine Learning']::text[], 'approved', false, NULL, '2026-05-20T19:35:24.530Z'),
('job-16', 'Cloud Solutions Architect', 'co-1', 'Google Cloud Platform', 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=100&auto=format&fit=crop&q=60', 'Singapore / Jakarta (Hybrid)', '$6,500 - $11,000 / month', 'Full-time', 'Senior Level', 'Help global tier-1 enterprise clients architecture secure, reliable, and scalable applications over GCP platform infrastructure, focusing on serverless migrations.', ARRAY['8+ years cloud implementation consulting experience', 'Active GCP Professional Cloud Security or Solutions Architect Certification', 'Highly technical in complex networking topology, Kubernetes cluster federations, and IAM setups']::text[], ARRAY['GCP', 'Cloud Architecture', 'Terraform', 'Kubernetes', 'BGP', 'IAM']::text[], 'approved', false, NULL, '2026-05-15T23:35:24.530Z'),
('job-17', 'Fullstack Laravel Developer (Kopi Kenangan App)', 'co-12', 'Kopi Kenangan', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 11.000.000 - Rp 18.000.000 / month', 'Full-time', 'Mid Level', 'Mengembangkan sistem loyalty member, digital vouchers order backend, serta integrasi pemesanan point of sales (POS) Kopi Kenangan seluruh Indonesia.', ARRAY['Minimal 3 tahun berkecimpung mengembangkan Fullstack PHP Laravel dan VueJS', 'Pengalaman matang integrasi payment gateway MIDTRANS atau XENDIT', 'Familiar dengan Redis queue worker untuk asynchronous transactional jobs']::text[], ARRAY['Laravel', 'Vue.js', 'PHP', 'Midtrans', 'Redis', 'MySQL']::text[], 'approved', false, NULL, '2026-05-16T23:35:24.530Z'),
('job-18', 'QA Automation Engineer', 'co-9', 'Shopee Indonesia', 'https://images.unsplash.com/photo-1472851294608-062f824d296e?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 12.000.000 - Rp 21.000.000 / month', 'Full-time', 'Mid Level', 'Menulis skrip uji otomatisasi komprehensif (E2E) menggunakan Cypress atau Selenium untuk memastikan kestabilan web checkout dari aneka bug.', ARRAY['2+ tahun pengalaman bekerja sebagai QA Engineer fokus otomatisasi uji', 'Kemampuan coding andal menggunakan JavaScript, TypeScript, atau Python', 'Pernah merancang integration test plan terhubung dengan Jenkins / CI pipeline']::text[], ARRAY['Cypress', 'JavaScript', 'Selenium', 'Jenkins', 'Appium', 'Integration Testing']::text[], 'approved', false, NULL, '2026-05-19T02:35:24.530Z'),
('job-19', 'Lead Product Manager - Core Transactions', 'co-5', 'Tokopedia', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 30.000.000 - Rp 52.000.000 / month', 'Full-time', 'Senior Level', 'Nakhodai visi produk, strategi rilis, serta kordinasi lintas fungsional (Engineering, Business, Design) untuk checkout cart core Tokopedia merchant transactions.', ARRAY['5+ tahun rekam jejak sukses sebagai Product Manager di sektor Fintech / E-commerce', 'Kemampuan analitis data (SQL, Google Analytics, Amplitude) tingkat lanjut', 'Komunikasi diplomatis andal melobi business requirements menjadi functional design']::text[], ARRAY['Product Strategy', 'Amplitude', 'SQL', 'Agile', 'User Research', 'Wireframes']::text[], 'approved', false, NULL, '2026-05-20T07:35:24.530Z'),
('job-20', 'Database Administrator DBA Specialist', 'co-8', 'Bank Mandiri', 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID / On-site', 'Rp 14.000.000 - Rp 23.000.000 / month', 'Full-time', 'Mid Level', 'Bertanggung jawab melakukan backup database Mandiri, replikasi data high-availability, optimasi query lambat, serta instalasi patch keamanan Oracle/Postgres db.', ARRAY['S1 Teknik Informatika/Sistem Informasi', 'Menguasai setup server Oracle Database, Microsoft SQL Server, atau PostgreSQL', 'Memahami arsitektur failover cluster, partisi tabel besar, serta optimasi indeks']::text[], ARRAY['Oracle DB', 'PostgreSQL', 'SQL Server', 'Database Indexing', 'Backup & Recovery']::text[], 'approved', false, NULL, '2026-05-17T15:35:24.530Z'),
('job-21', 'Frontend Developer (Angular / Vue)', 'co-2', 'Finverge Labs', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=60', 'Singapore / Hybrid', '$4,000 - $6,500 / month', 'Contract', 'Mid Level', 'Contract base developer to collaborate with back office ledger migration dashboard UI using Angular 17. Maintain high performance grid rendering.', ARRAY['At least 3 years commercial Angular experience', 'Great implementation of RXJS, state management, and unit testing using Jasmine/Karma', 'Fluency in English team discussions is mandatory']::text[], ARRAY['Angular', 'RxJS', 'TypeScript', 'Karma', 'Ngrx', 'Tailwind CSS']::text[], 'approved', false, NULL, '2026-05-16T09:35:24.530Z'),
('job-22', 'Developer Technical Writer Specialist', 'co-1', 'Google Cloud Platform', 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=100&auto=format&fit=crop&q=60', 'Remote (APAC)', '$4,500 - $7,000 / month', 'Contract', 'Mid Level', 'Draft, polish, and synthesize developer-facing tutorial guides, API schemas, and installation guides for Google Cloud Platform SDK integration plugins.', ARRAY['Outstanding technical writing portfolio in English (Markdown format)', 'Basic capabilities of reading multi-programming language snippets (Java, Go, Python, TypeScript)', 'Passionate about translating complex architectural systems into friendly clear tutorials']::text[], ARRAY['Technical Writing', 'Markdown', 'Git', 'API Documentation', 'Docusaurus', 'Technical Translation']::text[], 'approved', false, NULL, '2026-05-13T11:35:24.530Z'),
('job-23', 'Senior Live Streaming Systems Engineer', 'co-11', 'Vidio', 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 28.000.000 - Rp 45.000.000 / month', 'Full-time', 'Senior Level', 'Kembangkan video delivery pipeline latensi super rendah untuk saluran siaran sepak bola nasional Vidio, memanfaatkan protokol WebRTC, HLS, rtmp, serta CDN scaling.', ARRAY['5+ tahun rekam jejak solid di ranah video encoding / streaming systems', 'Paham mendalam atas FFmpeg, H.264/H.265 codecs, DASH, dan WebRTC protocols', 'Familiar dengan Go, C++, Rust atau Java untuk optimalisasi media server backend']::text[], ARRAY['WebRTC', 'HLS', 'FFmpeg', 'Go', 'CDN', 'C++']::text[], 'approved', false, NULL, '2026-05-20T16:35:24.530Z'),
('job-24', 'Social Media & Content Creator Lead', 'co-12', 'Kopi Kenangan', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID / On-site', 'Rp 8.000.000 - Rp 13.000.000 / month', 'Full-time', 'Mid Level', 'Buat ide-ide kampanye digital kreatif yang viral untuk mempromosikan menu baru Kopi Kenangan, membuat video TikTok/Instagram reels interaktif, dan berkolaborasi bersama influencer.', ARRAY['Min S1 Jurusan Komunikasi/Marketing/DKV atau pengalaman setara', 'Portofolio video TikTok/Reels kreatif dengan tingkat interaksi tinggi', 'Kemampuan editing video cepat di handphone / Adobe Premiere']::text[], ARRAY['Video Editing', 'Social Media', 'Creative Direction', 'Copywriting', 'TikTok Marketing']::text[], 'approved', false, NULL, '2026-05-08T11:35:24.530Z'),
('job-25', 'Scrum Master / Technical Delivery Agile Lead', 'co-7', 'Traveloka', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 14.000.000 - Rp 23.000.000 / month', 'Full-time', 'Mid Level', 'Fasilitasi sprint planning, standups harian, membuang hambatan developer, serta memoles komunikasi tim agar delivery siklus fitur hotel & akomodasi berjalan tepat waktu.', ARRAY['Sertifikasi Scrum Alliance (CSM / PSM I) adalah nilai tambah besar', 'Pernah mengarsiteki delivery timeline produk berdurasi minimal 2 tahun', 'Sangat fasih menggunakan JIRA, Confluence, dan tools pelacak defect']::text[], ARRAY['Scrum', 'Agile', 'Jira', 'Confluence', 'Sprint Management', 'Defect Tracking']::text[], 'approved', false, NULL, '2026-05-12T15:35:24.530Z'),
('job-26', 'Group HR Talent Acquisition Lead', 'co-6', 'GoTo Group', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 20.000.000 - Rp 35.000.000 / month', 'Full-time', 'Senior Level', 'Nakhodai program talenta rekrutmen teknologi strategis (Engineering & Product) skala nasional GoTo. Kembangkan kemitraan universitas dan program magang global.', ARRAY['5+ tahun pengalaman memimpin tim rekruter di regional skala besar / hypergrowth', 'Kemampuan menjalin talent pipeline andal di ranah Software Engineering', 'Terbiasa dengan tools Applicant Tracking System (ATS) mutakhir seperti Greenhouse']::text[], ARRAY['Recruitment', 'Greenhouse', 'Applicant Tracking System', 'Negotiation', 'Talent Pipeline']::text[], 'approved', false, NULL, '2026-05-18T21:35:24.280Z'),
('job-27', 'Senior Golang Backend Platform Engineer', 'co-9', 'Shopee Indonesia', 'https://images.unsplash.com/photo-1472851294608-062f824d296e?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 28.000.000 - Rp 48.000.000 / month', 'Full-time', 'Senior Level', 'Pahat sistem backend voucher kampanye puncak bulanan Shopee yang andal menelan trafik ratusan ribu QPS, mengedepankan efisiensi konkurensi di Golang.', ARRAY['5+ tahun keahlian backend komersial di Golang / C++', 'Pemahaman mumpuni sistem terdistribusi, load balancer, partisi database SQL dan caching Redis', 'Tangguh memecahkan masalah concurrency race condition menggunakan goroutines Profiling']::text[], ARRAY['Go', 'Redis', 'PostgreSQL', 'Microservices', 'Docker', 'Profiling']::text[], 'approved', false, NULL, '2026-05-20T08:35:24.530Z'),
('job-28', 'Data & ETL Integration Infrastructure Engineer', 'co-3', 'Veritas Analytics', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 16.000.000 - Rp 26.000.000 / month', 'Full-time', 'Senior Level', 'Membangun pipeline ETL/ELT pengolahan sekunder big data bernilai puluhan terabyte dengan Apache Spark, Airflow, Kafka, dan data warehouse Snowflake.', ARRAY['3+ tahun bekerja di ranah Data Engineering / ETL', 'Keahlian mumpuni menulis transform logic dengan Apache Spark, Python atau Scala', 'Familiar merangkai dag penjadwalan data pipeline di Apache Airflow']::text[], ARRAY['Python', 'Apache Spark', 'Kafka', 'Apache Airflow', 'Snowflake', 'SQL']::text[], 'approved', false, NULL, '2026-05-20T13:35:24.530Z'),
('job-29', 'Admin Executive & Office Intern', 'co-5', 'Tokopedia', 'https://images.unsplash.com/photo-1563013544-824ae1d704d3?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 4.000.000 - Rp 5.500.000 / month', 'Internship', 'Entry Level', 'Segarkan kecakapan organisasimu! Bantu menyusun berkas administratif kantor, mengkoordinir inventaris fasilitas, serta akomodasi kebutuhan umum tim regional.', ARRAY['Mahasiswa aktif / Fresh Graduate dari semua jurusan (Administrasi / Komunikasi lebih disukai)', 'Teliti, rapi dalam penataan folder digital, mahir Google Docs / Google Sheets', 'Memiliki interpersonal asertif yang sopan dan ramah']::text[], ARRAY['Google Sheets', 'Google Docs', 'Administration', 'Scheduling', 'Communication']::text[], 'approved', false, NULL, '2026-05-20T21:35:24.530Z'),
('job-30', 'Digital Marketing & SEO Coordinator', 'co-12', 'Kopi Kenangan', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=100&auto=format&fit=crop&q=60', 'Jakarta, ID', 'Rp 8.000.000 - Rp 12.000.000 / month', 'Full-time', 'Mid Level', 'Tingkatkan kunjungan pencarian organik website Kopi Kenangan, kelola kampanye digital marketing ads berbayar (Google Ads, Meta Ads) untuk mendongkrak unduh aplikasi mobile.', ARRAY['2+ tahun berkarier mengelola SEO Off-page/On-page & performance marketing', 'Mahir menganalisa Google Search Console, SEMrush, dan Google Analytics GA4', 'Kemampuan andal riset keyword kuliner potensial dengan ROI iklan positif']::text[], ARRAY['SEO', 'Google Ads', 'Meta Ads', 'Google Analytics', 'Keyword Research']::text[], 'approved', false, NULL, '2026-05-20T12:35:24.530Z')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, company_id = EXCLUDED.company_id, company_name = EXCLUDED.company_name, company_logo = EXCLUDED.company_logo, location = EXCLUDED.location, salary_range = EXCLUDED.salary_range, job_type = EXCLUDED.job_type, experience_level = EXCLUDED.experience_level, description = EXCLUDED.description, requirements = EXCLUDED.requirements, skills_required = EXCLUDED.skills_required, status = EXCLUDED.status, is_suspicious = EXCLUDED.is_suspicious, suspicious_reason = EXCLUDED.suspicious_reason, created_at = EXCLUDED.created_at;
